### ISSUE TITLE
关于i686

### ISSUE THREAD

**Issue by liusy58** [afterthat97/cool-compiler#2]
你好，请问你是怎么在ubuntu上面运行i686的代码的呀，我这边一直报错

**Comment by liusy58** [comment]
wsl 有毒

**Comment by Doraemonzzz** [comment]
@liusy58 
wsl好像不支持，要使用wsl2，然后运行如下指令
```
sudo dpkg --add-architecture i386
sudo apt-get update
sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386
```
我这边已经运行成功了。

参考资料：
https://stackoverflow.com/questions/42120938/exec-format-error-32-bit-executable-windows-subsystem-for-linux
